-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 11:44:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brp_local
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `budget` (
  `budget_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`budget_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_budget_name` ON `budget` (`name` ASC, `project_id` ASC, `year` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role` (
  `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `budget_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `location_id` BIGINT(20) NULL DEFAULT NULL,
  `rate` DECIMAL(6,2) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  CONSTRAINT `fk_role_budget`
    FOREIGN KEY (`budget_id`)
    REFERENCES `budget` (`budget_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10000000
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_role_budget_idx` ON `role` (`budget_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role_allocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_allocation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role_allocation` (
  `role_allocation_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `location_id` BIGINT(20) NULL,
  `resource_id` BIGINT(20) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `rate` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`role_allocation_id`),
  CONSTRAINT `fk_alloc_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_alloc_role_idx` ON `role_allocation` (`role_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role_allocation_fte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_allocation_fte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role_allocation_fte` (
  `role_allocation_id` BIGINT(20) NOT NULL,
  `type` VARCHAR(8) NOT NULL,
  `month` INT(11) NOT NULL,
  `fte` DECIMAL(6,2) NULL DEFAULT NULL,
  CONSTRAINT `fk_alloc_fte_aloc`
    FOREIGN KEY (`role_allocation_id`)
    REFERENCES `role_allocation` (`role_allocation_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_role_alloc_fte` ON `role_allocation_fte` (`role_allocation_id` ASC, `type` ASC, `month` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role_fte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_fte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role_fte` (
  `role_id` BIGINT(20) NOT NULL,
  `month` INT(11) NOT NULL,
  `fte` DECIMAL(6,2) NULL DEFAULT NULL,
  CONSTRAINT `fk_fte_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_role_fte` ON `role_fte` (`role_id` ASC, `month` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
