-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 12:59:22 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brp_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brp_local
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brp_local` DEFAULT CHARACTER SET latin1 ;
USE `brp_local` ;

-- -----------------------------------------------------
-- Table `budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget` ;

CREATE TABLE IF NOT EXISTS `budget` (
  `budget_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`budget_id`),
  UNIQUE INDEX `unq_budget_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `budget_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `location_id` BIGINT(20) NULL DEFAULT NULL,
  `rate` DECIMAL(6,2) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  INDEX `fk_role_budget` (`budget_id` ASC),
  CONSTRAINT `fk_role_budget`
    FOREIGN KEY (`budget_id`)
    REFERENCES `budget` (`budget_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10000000
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `role_allocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_allocation` ;

CREATE TABLE IF NOT EXISTS `role_allocation` (
  `role_allocation_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `location_id` BIGINT(20) NULL,
  `resource_id` BIGINT(20) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `rate` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`role_allocation_id`),
  INDEX `fk_alloc_role` (`role_id` ASC),
  CONSTRAINT `fk_alloc_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `role_allocation_fte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_allocation_fte` ;

CREATE TABLE IF NOT EXISTS `role_allocation_fte` (
  `role_allocation_id` BIGINT(20) NOT NULL,
  `type` VARCHAR(8) NOT NULL,
  `month` INT(11) NOT NULL,
  `fte` DECIMAL(6,2) NULL DEFAULT NULL,
  UNIQUE INDEX `unq_role_alloc_fte` (`role_allocation_id` ASC, `type` ASC, `month` ASC),
  CONSTRAINT `fk_alloc_fte_aloc`
    FOREIGN KEY (`role_allocation_id`)
    REFERENCES `role_allocation` (`role_allocation_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `role_fte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_fte` ;

CREATE TABLE IF NOT EXISTS `role_fte` (
  `role_id` BIGINT(20) NOT NULL,
  `month` INT(11) NOT NULL,
  `fte` DECIMAL(6,2) NULL DEFAULT NULL,
  UNIQUE INDEX `unq_role_fte` (`role_id` ASC, `month` ASC),
  CONSTRAINT `fk_fte_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
